name: first_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  bloc_concurrency: ^0.3.0
  meta: ^1.10.0
  equatable: ^2.0.5
  http: ^1.5.0
  carousel_slider: ^5.1.1
  google_fonts: ^6.3.1
  intl: ^0.20.2
  flutter_map: ^8.2.1
  positioned_tap_detector_2: ^1.0.4
  latlong2: ^0.9.1
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.2.4
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  loading_animation_widget: ^1.3.0
  add_to_cart_animation: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/imagen1.jpeg
    - assets/imagen2.jpeg
    - assets/imagen3.jpeg
    - assets/imagen4.png
    - assets/imagen5.png
    - assets/imagen6.png
    - assets/facebook.png
    - assets/instagram.png
    - assets/whatsapp.png
    - assets/products.json
    - assets/Hamburguesa sencilla.jpg
    - assets/Hamburguesa BBQ.jpeg
    - assets/Pizza margarita.jpg
    - assets/Pizza pepperoni.jpg
    - assets/Ensalada Cesar.jpg
    - assets/Ensalada Mediterranea.jpg
    - assets/Tacos al Pastor.jpg
    - assets/Tacos de Pollo.jpg
    - assets/Hamburgesa Doble Queso.jpeg
    - assets/Pizza Hawiana.jpg
    - assets/Ensalada de Atun.jpg
    - assets/Tacos Veganos.jpg
    - assets/domicilio moto.jpg
    - assets/bebida.jpg
    - assets/carro_vacio.jpeg
    - assets/logoredondo.png
    - assets/imagen8.png
    - assets/promocion1.webp
    - assets/promocion2.jpg
    - assets/promocion3.webp
    - assets/loogo.jpg
    - assets/logobitevia.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.ico"
